### ISSUE TITLE
Results for managers

### ISSUE THREAD

**Issue by nicojs** [infosupport/tech-survey#13]
Be able to search for results based on the question.

**Comment by nicojs** [comment]
See https://github.com/nicojs/rock-solid/blob/main/packages/backend/src/auth/office365-strategy.ts#L46 for an example of how to query for membership (this is not a nextjs app)

**Comment by JurreBrandsenInfoSupport** [comment]
Construct a table categorizing individuals by question, detailing their expertise levels as experts, proficient, or competent in the respective technologies.
